### ISSUE TITLE
LVGL examples, do they work?

### ISSUE THREAD

**Issue by hpssjellis** [arduino-libraries/Arduino_Pro_Tutorials#17]
@sebromero 

I feel like none of the LVGL examples work.  Can someone try one of them such as:

https://github.com/arduino-libraries/Arduino_Pro_Tutorials/blob/main/examples/Creating%20GUIs%20with%20LVGL/lvglCounter/lvglCounter.ino

and report back if they work for you on the PortentaH7. I am using MBED core 2.5.2 and LVGL library 8.0.2

For me nothing compiles, I haven't even go around to connecting any USB HUB cables.

**Comment by per1234** [comment]
>LVGL library 8.0.2

The example specifies that 7.11 should be used:
https://github.com/arduino-libraries/Arduino_Pro_Tutorials/blob/main/examples/Creating%20GUIs%20with%20LVGL/lvglCounter/lvglCounter.ino#L2
```cpp
/*
    Using LVGL v7.11
*/
```
The sketch compilation test done by the continuous integration system uses version 7.11.0 and compiles the example successfully:
https://github.com/arduino-libraries/Arduino_Pro_Tutorials/runs/3706391688?check_suite_focus=true#step:3:230

**Comment by sebromero** [comment]
Hi @hpssjellis ! Looks like there were some API changes in the new version of the LVGL library. Try with 7.11 as @per1234 pointed out.

**Comment by hpssjellis** [comment]
@per1234 and @sebromero you are correct it does mention to use version 7.11 of LVGL.h. I think I started with the Portenta examples Portenta_lvgl  which did not have the reminder, and still doesn't compile seems to have issues finding  ```lv_conf.h```

 Deprecation is the bane of TechEd. 

Is there some other graphics library we could use such as [Adafruit_GFX](https://learn.adafruit.com/adafruit-gfx-graphics-library)  for doing some graphics on a computer display?

**Comment by marqdevx** [comment]
Hey @hpssjellis we pointed the version used but my plans were to update the sketch and tutorial to fit the new API.

The LVGL examples from the Core need to be updated, I will do it.

Follow the tutorial of the LVGL, you just need to `#include "Portenta_LittleVGL.h"`

* Tutorial: https://docs.arduino.cc/tutorials/portenta-h7/por-ard-lvgl
* Sketch: https://github.com/arduino-libraries/Arduino_Pro_Tutorials/blob/v1.0.4/examples/Creating%20GUIs%20with%20LVGL/lvglCounter/lvglCounter.ino

I will make a branch with a working sketch with the LVGL@v8

**Comment by hpssjellis** [comment]
Thanks @marqdevx the counter example using LVGL@7.11 works great, but even with  ```#include "Portenta_LittleVGL.h"``` I can't get the Arduino_MBED example  [Portenta_lvgl.ino](https://github.com/arduino/ArduinoCore-mbed/blob/master/libraries/LittleVGL/examples/Portenta_lvgl/Portenta_lvgl.ino) working it seems to have 2 other issues. One is line 92 where SRCL should be SCROLLABLE. and then some other issue. Any hints about it.  

If you do get LVGL@v8 working that would be great.

Also, is this doable from both M7 and M4 or only from M7?

**Comment by marqdevx** [comment]
Im aware of the examples of the Core, thanks for remind it. I will make a PR, hopefully they will be fixed for the next release :) 

I've tried it before and its working, just need to make those small changes.

Working from both individually, you could use RPC to make changes from M7 to M4(or vice versa). but you should only have one LVGL "manager" (if im not wrong, I will check that asap).

**Comment by sebromero** [comment]
> Is there a way to make the portenta use the latest LVGL library?

@hpssjellis As @marqdevx mentioned, the example needs to be adapted, but the library itself should work/compile fine. If you feel like, you could have a look at the LVGL changelog [here](https://docs.lvgl.io/8.0/CHANGELOG.html) and adjust the example accordingly so it reflects the API changes.
The underlying issues is that our libraries don't have versioned dependency management. So we can't specify with which version a library is compatible with. This would solve all these issues. One day we'll have it...

**Comment by hpssjellis** [comment]
@marqdevx just post here when it is ready to test or the PR has been accepted. 

 @sebromero I agree version control would make examples much more stable. I always use versions when using javascript and npm. 

```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@2.3.0"> </script> 
```

LOL, TensorflowJS is now at version 3.9.0


It is ridiculous how fast examples and videos can be deprecated, and makes teaching the subject a miserable experience.


Good luck updating the examples!

**Comment by hpssjellis** [comment]
@marqdevx @sebromero I am testing LVGL with Arduino Verison 3.0.1 and LVGL version 8.   Not having much success with the Portenta Board examples, just testing the counter now.

**Comment by marqdevx** [comment]
Hey @hpssjellis !
I will have a look to the `Portenta-board LVGL` sketch

But right now the Counter sketch inside `Arduino_Pro_Tutorials` it is only compatible with LVGL v7
https://github.com/arduino-libraries/Arduino_Pro_Tutorials/blob/main/examples/Creating%20GUIs%20with%20LVGL/lvglCounter/lvglCounter.ino#L2

In v8 they changed the task management, so I will make a port of the counter sketch and try to make clearer the example inside the Core Examples.

:)

**Comment by hpssjellis** [comment]
@marqdevx Thanbk you for looking into this. It is the last program needed for my course on The Portenta [Maker100](https://github.com/hpssjellis/maker100)  

I find the coding very alien, any chance you could make 1 program that just puts text and a line on the screen. That would be a great starting point for my students.

Another amazing starter would be Portenta Vision shield camera output, with text and a line on it.

**Comment by marqdevx** [comment]
You have good examples from LVGL at https://docs.lvgl.io/master/examples.html

A basic "Hello World" label would be:
```
    lv_obj_t * label = lv_label_create(lv_scr_act());     /*Add a label to the button*/
    lv_label_set_text(label, "Hello World");                /*Set the labels text*/
    lv_obj_center(label);
```

I will check if I can simplify/beautify it a little.

Thanks for your suggestion! :)

**Comment by PRT1986** [comment]
I would also really enjoy some simple examples showing how to create texts, colors and buttons. 
Further on a example integrating usb-c touch screen feedback to the Portenta to control a LED or Serial output

**Comment by marqdevx** [comment]
@hpssjellis could you please check if with both latest Core version and LGVL does this example work for you?
https://github.com/arduino-libraries/Arduino_Pro_Tutorials/blob/marqdevx/lvgl-v8/examples/Creating%20GUIs%20with%20LVGL/lvglCounter/lvglCounter.ino

LVGL v7 wasn't working for me.

**Comment by hpssjellis** [comment]
Can someone else also test this code from @marqdevx  https://github.com/arduino-libraries/Arduino_Pro_Tutorials/blob/marqdevx/lvgl-v8/examples/Creating%20GUIs%20with%20LVGL/lvglCounter/lvglCounter.ino

I don't really trust my USB-C to HDMI converter connections until I see it working. Perhaps @sebromero or @PRT1986  when you get time.


Mine compiles, but gives a strange flashing green when connected to HDMI.

**Comment by PRT1986** [comment]
Counter version worked for me with LVGL 7.11 library firmware, not tested anything else at this stage

**Comment by hpssjellis** [comment]
Thank you @PRT1986 
Was that with Arduino MBED version 3.0.1?

**Comment by PRT1986** [comment]
![image](https://user-images.githubusercontent.com/103249401/162670717-f713fda3-74be-41dd-aa5a-b82b7b228571.png)

**Comment by PRT1986** [comment]
IDE 1.8.19

**Comment by marqdevx** [comment]
I've tried LVGL 8.2.0 and v7.11.0 with mbed_portenta 3.1.0 and they work fine 🤔 
@hpssjellis if still not working for you try to update the bootloader just in case.
let me know!

**Comment by hpssjellis** [comment]
Thanks @marqdevx and @per1234 my main skill is messing up everything before my students try it! This issue is definitely on my side either my screen or connector. Still interested @marqdevx if you can get that basic text and line example going. I will fix things on my end.

**Comment by marqdevx** [comment]
> You have good examples from LVGL at https://docs.lvgl.io/master/examples.html
> 
> A basic "Hello World" label would be:
> 
> ```
>     lv_obj_t * label = lv_label_create(lv_scr_act());     /*Add a label to the button*/
>     lv_label_set_text(label, "Hello World");                /*Set the labels text*/
>     lv_obj_center(label);
> ```
> 
> I will check if I can simplify/beautify it a little.
> 
> Thanks for your suggestion! :)

This is the basic text code. You can use the examples from LVGL docs.
I will note this LVGL "request" right now we have some other priorities, I will ping you one the LVGL things that we make :)
