### ISSUE TITLE
Request for examples

### ISSUE THREAD

**Issue by wbadry** [arduino-libraries/Arduino_Pro_Tutorials#3]
Hello,
Is it possible to add examples for:

- Classic Bluetooth example (not BLE).
- SDIO example ( faster write than SPI).

If not mistaken , the **LBEE5KL1DX** supports classic Bluetooth. Also, **LBEE5KL1DX-883** is used for SDIO is also on Portenta schematic  

Reference:
https://content.arduino.cc/assets/Arduino-PortentaH7-schematic-V1.0.pdf

**Comment by marqdevx** [comment]
@wbadry This repo/library only wraps the sketches used on the tutorials at docs.arduino.cc (only the PRO boards)
We will note those suggestions, thanks 👍
