### ISSUE TITLE
Portenta H7: USB_CORE_ID_HS core only runs as usbhost for ~30s then hangs (LEDKeyboardController)

### ISSUE THREAD

**Issue by stickybun** [arduino-libraries/Arduino_Pro_Tutorials#33]
Running the LEDKeyboardController.ino example, only runs for ~30seconds (sometimes shorter), then hangs when running on the USB-C (HS) core. Sometimes shows the message "RHUB HS:0      Disable 4", sometimes not.

The FS core appears to work fine (USB-A connector requiring a breakout board).

Portenta H7, connected a USB keyboard directly (no-hub) via USB-C -> USB-A adapter, and enabling supplyPowerOnVBUS.

```log
RHUB HS:0      Connect
RHUB HS:0      Enable
DEV  HS.00     Allocate pipe, in = 0, out = 1
DEV  HS.01     Re-allocate pipe, in = 0, out = 1
DEV  HS.01     LS device, VID:413c PID:2113
ITF  HS.01.0-0 HID interface init
ITF  HS.01.0-0 Ep in 81
ITF  HS.01.1-1 HID interface init
ITF  HS.01.1-1 Ep in 82
DEV  HS.01     Device has 2 interfaces
....
r


r

r

r
RHUB HS:0      Disable 4
```

**Comment by stickybun** [comment]
Think this is a problem with the arudinocore-mbed usbhost code, so have posted it there: https://github.com/arduino/ArduinoCore-mbed/issues/725

**Comment by aentinger** [comment]
Closing, due to issue being tracked at https://github.com/arduino/ArduinoCore-mbed/issues/725 .
